export type artData = {
  slug: string;
  src: string;
  title: string;
  tag: string[];
  href?: string;
  description: string;
};
export const artworks: Array<artData> = [
  {
    slug: "manken_poster_2024",
    src: "/images/artworks/manken_poster_2024.png",
    title: "漫画研究会新歓ポスター",
    tag: ["Krita", "Manken"],
    description: "漫画研究会の2024年度新歓ポスター",
  },
  {
    slug: "zugadan_poster_2024",
    src: "/images/artworks/zugadan_poster_2024.png",
    title: "図画団新歓ポスター",
    tag: ["Krita", "Zugadan"],
    description: "筑波大学図画団の2024年度新歓ポスター",
  },
  {
    slug: "ink_drop",
    src: "/images/artworks/ink_drop.png",
    title: "Ink drop",
    tag: ["Krita", "Zugadan"],
    href: "https://www.instagram.com/p/Cy86MEcvrdo/",
    description: "水中に垂らされていく、金魚の形を成した墨滴",
  },
  {
    slug: "helios",
    src: "/images/artworks/helios.png",
    title: "Helios",
    tag: ["Krita", "Character"],
    href: "https://www.instagram.com/p/Cvlk3miR3NH/",
    description: "Warrior of the Sun",
  },
  {
    slug: "medusa",
    src: "/images/artworks/medusa.png",
    title: "Medusa",
    tag: ["Krita", "Character"],
    href: "https://www.instagram.com/p/CvW-p4zvlll/",
    description: "黒蛇使いの少女",
  },
  {
    slug: "eagle",
    src: "/images/artworks/eagle.png",
    title: "ワシの戦士",
    tag: ["Krita", "Character"],
    href: "https://www.instagram.com/p/Cqknaevvhac/",
    description: "ジェットエンジンを背負った空の戦士",
  },
  {
    slug: "masterpiece",
    src: "/images/artworks/masterpiece.png",
    title: "The Creator",
    tag: ["Krita", "Character"],
    href: "https://twitter.com/omemoji_art/status/1641262352556519424",
    description: "絵筆を持った神",
  },
  {
    slug: "celestial_maiden",
    src: "/images/artworks/celestial_maiden.png",
    title: "天女",
    tag: ["Krita", "Girl", "Character"],
    href: "https://www.instagram.com/p/Cp7uUD9vlLD/",
    description: "絵の具を自在に操る天女",
  },
  {
    slug: "white_snake",
    src: "/images/artworks/white_snake.png",
    title: "白蛇",
    tag: ["Krita"],
    href: "https://www.instagram.com/p/CpvBorxPl-x/",
    description: "A Japanese white snake",
  },
  {
    slug: "2023",
    src: "/images/artworks/2023.png",
    title: "2023 Happy New Year! ",
    tag: ["Inkscape", "New_Year"],
    href: "https://inkscape.org/~omemoji/%E2%98%85moon",
    description: "2023年の年賀状",
  },
  {
    slug: "lux",
    src: "/images/artworks/lux.png",
    title: "Lux",
    tag: ["Krita", "Character"],
    href: "https://www.instagram.com/p/CmwruKfvP-v",
    description: "がらくたで構成された、かわいい猫の姫",
  },
  {
    slug: "zugadanten2022",
    src: "/images/artworks/zugadanten2022.jpg",
    title: "図画団展2022",
    tag: ["Krita", "Zugadan", "Bird"],
    href: "https://www.instagram.com/p/CkSHtqIBGFx/",
    description: "2022年度図画団展のポスター",
  },
  {
    slug: "rainbow_dragon",
    src: "/images/artworks/rainbow_dragon.png",
    title: "虹龍",
    tag: ["Krita", "Dragon"],
    href: "https://www.instagram.com/p/Cb1wksDvX-i/",
    description: "極彩色の龍",
  },
  {
    slug: "harvest",
    src: "/images/artworks/harvest.png",
    title: "やまぶどう",
    tag: ["Krita", "Bird"],
    href: "https://www.instagram.com/p/CbeI9z3v0HT/",
    description: "秋のやまぶどうとカラス",
  },
  {
    slug: "2022",
    src: "/images/artworks/2022.png",
    title: "2022 Happy New Year! ",
    tag: ["Krita", "New_Year"],
    href: "https://www.instagram.com/p/CYJtB4bP9LA/",
    description: "年賀状",
  },
  {
    slug: "god_of_swords",
    src: "/images/artworks/god_of_swords.png",
    title: "剣神",
    tag: ["Krita"],
    href: "https://www.instagram.com/p/CW18LCxvxYe/",
    description: "虹の剣を持つ神",
  },
  {
    slug: "tower_girl",
    src: "/images/artworks/tower_girl.png",
    title: "鉄塔少女",
    tag: ["Inkscape", "Girl"],
    href: "https://inkscape.org/~omemoji/%E2%98%85+29",
    description: "夕暮れの鉄塔に佇む少女",
  },
  {
    slug: "the_end_of_fall",
    src: "/images/artworks/the_end_of_fall.png",
    title: "The end of fall",
    tag: ["Inkscape", "Bird"],
    href: "https://inkscape.org/~omemoji/%E2%98%85the-end-of-fall",
    description: "紅葉と透き通った湖面",
  },
  {
    slug: "RGBdragon",
    src: "/images/artworks/RGBdragon.png",
    title: "RGBdragon",
    tag: ["Inkscape", "Dragon"],
    href: "https://inkscape.org/~omemoji/%E2%98%85rgbdragon",
    description: "光の三原色に彩られた龍",
  },
  {
    slug: "shinkan-cover",
    src: "/images/artworks/shinkan-cover.png",
    title: "SHINKAN Booklet 2021",
    tag: ["Adobe_Illustrator", "Bird"],
    href: "",
    description: "2021年度情報科学類新歓パンフレットの表紙",
  },
  {
    slug: "skyblue",
    src: "/images/artworks/skyblue.png",
    title: "skyblue",
    tag: ["Adobe_Illustrator", "Girl"],
    href: "",
    description: "音楽を奏でるクジラと少女",
  },
  {
    slug: "asoblock_dragon",
    src: "/images/artworks/asoblock_dragon.jpg",
    title: "自在龍",
    tag: ["Asoblock", "Dragon"],
    href: "https://www.asoblock.jp/webzukan/detail.php?id=160",
    description: "アソブロックで作成した龍",
  },
  {
    slug: "blazing_leaves",
    src: "/images/artworks/blazing_leaves.jpg",
    title: "Blazing leaves",
    tag: ["Acryl", "Analog", "School"],
    href: "",
    description: "高校生国際美術展に応募したもの",
  },
];
